/* This file is generated from the reviewed English Settings Language defaults.
 * Regenerate only when those defaults change; storefront variables are preserved verbatim.
 */

export const SETTINGS_LANGUAGE_SOURCE_TEXT = [
  "Items",
  "Retail Price",
  "You Save",
  "Add To Box",
  "Next",
  "Add To Cart",
  "Total",
  "View Selected Products",
  "off",
  "item(s)",
  "Select Subscription Plan",
  "No Products Available",
  "Choose Options",
  "Load More Products",
  "Preparing Bundle...",
  "Redirecting...",
  "Added",
  "Add",
  "Review",
  "Select Bundle Products",
  "Quantity",
  "Are you sure?",
  "Are you sure you want to clear all items from your cart? This action cannot be undone...",
  "Clear",
  "Cancel",
  "Clear Cart",
  "Remove {{boxSelectionDifference}} item(s) to select this box",
  "Remove This Product From {{stepName}}",
  "Add at least {{conditionQuantity}} products on this step",
  "Add a maximum of {{conditionQuantity}} products to continue",
  "Add exactly {{conditionQuantity}} products on this step",
  "Add products worth at least {{conditionAmount}} on this step",
  "Add products worth maximum of {{conditionAmount}} on this step",
  "Add products worth {{conditionAmount}} on this step",
  "Add products weighing at least {{conditionWeight}} on this step",
  "Add products weighing maximum of {{conditionWeight}} on this step",
  "Add products weighing {{conditionWeight}} on this step",
  "Add a maximum of {{maxAllowedAddons}} addon products on this step",
  "Addon product is mandatory on this step",
  "Additional offers to be unlocked",
  "Add to Cart",
  "Select variant",
  "Added x{{allowedQuantity}}",
  "Add +",
  "Select {{quantityDifference}} Items",
  "View Bundle Items",
  "Selected Products",
  "Subtotal",
  "Add Bundle to Cart",
  "Prev",
  "Done",
  "Adding Bundle...",
  "Bundle Added",
  "Product",
  "Show all steps",
  "No More Stock"
] as const;

export const SETTINGS_LANGUAGE_TRANSLATIONS: Record<string, readonly string[]> = {
  "ar": [
    "أغراض",
    "سعر التجزئة",
    "أنت أحفظ",
    "أضف إلى الصندوق",
    "التالي",
    "أضف إلى السلة",
    "المجموع",
    "عرض المنتجات المختارة",
    "عن",
    "أغراض)",
    "حدد خطة الاشتراك",
    "لا توجد منتجات متاحة",
    "اختر الخيارات",
    "تحميل المزيد من المنتجات",
    "تحضير الحزمة...",
    "إعادة التوجيه...",
    "تمت الإضافة",
    "يضيف",
    "مراجعة",
    "حدد منتجات الحزمة",
    "كمية",
    "هل أنت متأكد؟",
    "هل أنت متأكد أنك تريد مسح كافة العناصر من سلة التسوق الخاصة بك؟ لا يمكن التراجع عن هذا الإجراء...",
    "واضح",
    "يلغي",
    "عربة واضحة",
    "قم بإزالة {{boxSelectionDifference}} عنصر (عناصر) لتحديد هذا المربع",
    "قم بإزالة هذا المنتج من {{stepName}}",
    "قم بإضافة {{conditionQuantity}} منتج على الأقل في هذه الخطوة",
    "قم بإضافة {{conditionQuantity}} منتج كحد أقصى للمتابعة",
    "أضف بالضبط {{conditionQuantity}} منتج في هذه الخطوة",
    "أضف منتجات بقيمة {{conditionAmount}} على الأقل في هذه الخطوة",
    "أضف منتجات بقيمة {{conditionAmount}} كحد أقصى في هذه الخطوة",
    "أضف منتجات بقيمة {{conditionAmount}} في هذه الخطوة",
    "أضف منتجات لا يقل وزنها عن {{conditionWeight}} في هذه الخطوة",
    "أضف منتجات بوزن أقصى {{conditionWeight}} في هذه الخطوة",
    "أضف منتجات بوزن {{conditionWeight}} في هذه الخطوة",
    "أضف بحد أقصى {{maxAllowedAddons}} منتجًا إضافيًا في هذه الخطوة",
    "المنتج الإضافي إلزامي في هذه الخطوة",
    "عروض إضافية ليتم فتحها",
    "أضف إلى السلة",
    "حدد البديل",
    "تمت الإضافة إلى x{{allowedQuantity}}",
    "أضف +",
    "حدد {{quantityDifference}} العناصر",
    "عرض عناصر الحزمة",
    "منتجات مختارة",
    "المجموع الفرعي",
    "أضف الحزمة إلى سلة التسوق",
    "السابق",
    "منتهي",
    "جارٍ إضافة الحزمة...",
    "تمت إضافة الحزمة",
    "منتج",
    "إظهار كافة الخطوات",
    "لا مزيد من المخزون"
  ],
  "bg-BG": [
    "Предмети",
    "Цена на дребно",
    "Вие спестявате",
    "Добавяне към кутията",
    "Следваща",
    "Добавяне в количката",
    "Общо",
    "Вижте избраните продукти",
    "изключено",
    "артикул(и)",
    "Изберете Абонаментен план",
    "Няма налични продукти",
    "Изберете Опции",
    "Зареждане на още продукти",
    "Пакетът се подготвя...",
    "Пренасочва се...",
    "Добавено",
    "Добавете",
    "Преглед",
    "Изберете Пакетни продукти",
    "Количество",
    "сигурен ли си",
    "Сигурни ли сте, че искате да изчистите всички артикули от количката си? Това действие не може да бъде отменено...",
    "ясно",
    "Отказ",
    "Изчистване на количката",
    "Премахнете {{boxSelectionDifference}} елемент(а), за да изберете това поле",
    "Премахнете този продукт от {{stepName}}",
    "Добавете поне {{conditionQuantity}} продукта на тази стъпка",
    "Добавете максимум {{conditionQuantity}} продукта, за да продължите",
    "Добавете точно {{conditionQuantity}} продукта на тази стъпка",
    "Добавете продукти на стойност поне {{conditionAmount}} на тази стъпка",
    "Добавете продукти на максимална стойност {{conditionAmount}} на тази стъпка",
    "Добавете продукти на стойност {{conditionAmount}} на тази стъпка",
    "Добавете продукти с тегло най-малко {{conditionWeight}} на тази стъпка",
    "Добавете продукти с максимално тегло {{conditionWeight}} на тази стъпка",
    "Добавете продукти с тегло {{conditionWeight}} на тази стъпка",
    "Добавете максимум {{maxAllowedAddons}} допълнителни продукта на тази стъпка",
    "Допълнителният продукт е задължителен на тази стъпка",
    "Допълнителни оферти за отключване",
    "Добавяне в количката",
    "Изберете вариант",
    "Добавен x{{allowedQuantity}}",
    "Добавете +",
    "Изберете {{quantityDifference}} артикули",
    "Преглед на елементи от пакета",
    "Избрани продукти",
    "Междинна сума",
    "Добавете пакет към количката",
    "предишна",
    "Готово",
    "Пакетът се добавя...",
    "Пакетът е добавен",
    "Продукт",
    "Покажи всички стъпки",
    "Няма повече запаси"
  ],
  "ca": [
    "Elements",
    "Preu al detall",
    "Tu estalvies",
    "Afegeix a la caixa",
    "A continuació",
    "Afegeix a la cistella",
    "Total",
    "Veure els productes seleccionats",
    "apagat",
    "article(s)",
    "Seleccioneu Pla de subscripció",
    "No hi ha productes disponibles",
    "Trieu Opcions",
    "Carregueu més productes",
    "S'està preparant el paquet...",
    "S'està redirigint...",
    "Afegit",
    "Afegeix",
    "Revisió",
    "Seleccioneu Paquets de productes",
    "Quantitat",
    "N'estàs segur?",
    "Esteu segur que voleu esborrar tots els articles del vostre carretó? Aquesta acció no es pot desfer...",
    "Clar",
    "Cancel·la",
    "Esborra el carro",
    "Elimineu {{boxSelectionDifference}} element(s) per seleccionar aquesta casella",
    "Traieu aquest producte de {{stepName}}",
    "Afegiu almenys {{conditionQuantity}} productes en aquest pas",
    "Afegiu un màxim de {{conditionQuantity}} productes per continuar",
    "Afegiu exactament {{conditionQuantity}} productes en aquest pas",
    "Afegiu productes amb un valor mínim de {{conditionAmount}} en aquest pas",
    "Afegiu productes amb un valor màxim de {{conditionAmount}} en aquest pas",
    "Afegiu productes per valor de {{conditionAmount}} en aquest pas",
    "Afegiu productes que pesin almenys {{conditionWeight}} en aquest pas",
    "Afegiu productes amb un pes màxim de {{conditionWeight}} en aquest pas",
    "Afegiu productes que pesin {{conditionWeight}} en aquest pas",
    "Afegiu un màxim de {{maxAllowedAddons}} productes addicionals en aquest pas",
    "El producte addicional és obligatori en aquest pas",
    "Ofertes addicionals per desbloquejar",
    "Afegeix a la cistella",
    "Seleccioneu la variant",
    "S'ha afegit x{{allowedQuantity}}",
    "Afegeix +",
    "Seleccioneu {{quantityDifference}} Elements",
    "Veure articles del paquet",
    "Productes seleccionats",
    "Subtotal",
    "Afegeix el paquet al carretó",
    "Anterior",
    "Fet",
    "S'està afegint un paquet...",
    "Paquet afegit",
    "Producte",
    "Mostra tots els passos",
    "No més estoc"
  ],
  "zh-CN": [
    "项目",
    "零售价",
    "您保存",
    "添加到框",
    "下一个",
    "添加到购物车",
    "全部的",
    "查看精选产品",
    "离开",
    "项目）",
    "选择订阅计划",
    "无可用产品",
    "选择选项",
    "加载更多产品",
    "正在准备捆绑包...",
    "正在重定向...",
    "额外",
    "添加",
    "审查",
    "选择捆绑产品",
    "数量",
    "你确定吗？",
    "您确定要清除购物车中的所有商品吗？此操作无法撤消...",
    "清除",
    "取消",
    "清除购物车",
    "删除 {{boxSelectionDifference}} 项以选择此框",
    "从 {{stepName}} 中删除该产品",
    "在此步骤中添加至少 {{conditionQuantity}} 个产品",
    "最多添加 {{conditionQuantity}} 个产品以继续",
    "在此步骤中准确添加 {{conditionQuantity}} 个产品",
    "在此步骤添加至少价值 {{conditionAmount}} 的产品",
    "在此步骤添加最大价值 {{conditionAmount}} 的产品",
    "在此步骤添加价值 {{conditionAmount}} 的产品",
    "在此步骤添加重量至少为 {{conditionWeight}} 的产品",
    "在此步骤添加最大重量为 {{conditionWeight}} 的产品",
    "在此步骤添加重量为 {{conditionWeight}} 的产品",
    "此步骤最多添加 {{maxAllowedAddons}} 个插件产品",
    "插件产品在此步骤中是必需的",
    "额外优惠待解锁",
    "添加到购物车",
    "选择变体",
    "添加了 x{{allowedQuantity}}",
    "添加+",
    "选择{{quantityDifference}}项目",
    "查看捆绑项目",
    "精选产品",
    "小计",
    "将捆绑包添加到购物车",
    "上一篇",
    "完毕",
    "添加捆绑包...",
    "已添加捆绑包",
    "产品",
    "显示所有步骤",
    "没有更多库存"
  ],
  "zh-TW": [
    "專案",
    "零售價",
    "您儲存",
    "新增到框",
    "下一個",
    "加入購物車",
    "全部的",
    "查看精選商品",
    "離開",
    "專案)",
    "選擇訂閱計劃",
    "無可用產品",
    "選擇選項",
    "載入更多產品",
    "正在準備捆綁包...",
    "正在重定向...",
    "額外",
    "添加",
    "審查",
    "選擇捆綁產品",
    "數量",
    "你確定嗎？",
    "您確定要清除購物車中的所有商品嗎？此操作無法撤銷...",
    "清除",
    "取消",
    "清除購物車",
    "刪除 {{boxSelectionDifference}} 項以選擇此框",
    "從 {{stepName}} 中刪除該產品",
    "在此步驟中增加至少 {{conditionQuantity}} 個產品",
    "最多增加 {{conditionQuantity}} 個產品以繼續",
    "在此步驟中準確增加 {{conditionQuantity}} 個產品",
    "在此步驟添加至少價值 {{conditionAmount}} 的產品",
    "在此步驟增加最大價值 {{conditionAmount}} 的產品",
    "在此步驟添加價值 {{conditionAmount}} 的產品",
    "在此步驟中添加重量至少為 {{conditionWeight}} 的產品",
    "在此步驟增加最大重量為 {{conditionWeight}} 的產品",
    "在此步驟添加重量為 {{conditionWeight}} 的產品",
    "此步驟最多新增 {{maxAllowedAddons}} 個外掛程式產品",
    "插件產品在此步驟中是必需的",
    "額外優惠待解鎖",
    "加入購物車",
    "選擇變體",
    "新增了 x{{allowedQuantity}}",
    "添加+",
    "選擇{{quantityDifference}}項目",
    "查看捆綁項目",
    "精選商品",
    "小計",
    "將捆綁包加入購物車",
    "上一篇",
    "完畢",
    "新增捆綁包...",
    "已新增捆綁包",
    "產品",
    "顯示所有步驟",
    "沒有更多庫存"
  ],
  "hr": [
    "Predmeti",
    "Maloprodajna cijena",
    "Vi štedite",
    "Dodaj u okvir",
    "Sljedeći",
    "Dodaj u košaricu",
    "Ukupno",
    "Pogledajte odabrane proizvode",
    "isključeno",
    "predmet(i)",
    "Odaberite Plan pretplate",
    "Nema dostupnih proizvoda",
    "Odaberite Opcije",
    "Učitaj više proizvoda",
    "Priprema paketa...",
    "Preusmjeravanje...",
    "Dodano",
    "Dodati",
    "Pregled",
    "Odaberite Skupni proizvodi",
    "Količina",
    "Jeste li sigurni?",
    "Jeste li sigurni da želite poništiti sve artikle iz svoje košarice? Ova se radnja ne može poništiti...",
    "Jasan",
    "Otkazati",
    "Očisti košaricu",
    "Uklonite {{boxSelectionDifference}} stavki da odaberete ovaj okvir",
    "Uklonite ovaj proizvod s {{stepName}}",
    "Dodajte najmanje {{conditionQuantity}} proizvoda u ovom koraku",
    "Za nastavak dodajte najviše {{conditionQuantity}} proizvoda",
    "Dodajte točno {{conditionQuantity}} proizvoda na ovom koraku",
    "U ovom koraku dodajte proizvode u vrijednosti od najmanje {{conditionAmount}}",
    "U ovom koraku dodajte proizvode u vrijednosti od najviše {{conditionAmount}}",
    "Dodajte proizvode u vrijednosti {{conditionAmount}} na ovom koraku",
    "U ovom koraku dodajte proizvode težine najmanje {{conditionWeight}}",
    "U ovom koraku dodajte proizvode maksimalne težine {{conditionWeight}}",
    "U ovom koraku dodajte proizvode težine {{conditionWeight}}",
    "U ovom koraku dodajte najviše {{maxAllowedAddons}} dodatnih proizvoda",
    "Dodatni proizvod obavezan je u ovom koraku",
    "Dodatne ponude za otključavanje",
    "Dodaj u košaricu",
    "Odaberite varijantu",
    "Dodano x{{allowedQuantity}}",
    "Dodaj +",
    "Odaberite stavke {{quantityDifference}}",
    "Pregledajte stavke paketa",
    "Odabrani proizvodi",
    "Međuzbroj",
    "Dodajte paket u košaricu",
    "Pret",
    "Gotovo",
    "Dodavanje paketa...",
    "Paket dodan",
    "Proizvod",
    "Prikaži sve korake",
    "Nema više zaliha"
  ],
  "cs": [
    "Položky",
    "Maloobchodní cena",
    "Ušetříte",
    "Přidat do pole",
    "Další",
    "Přidat do košíku",
    "Celkový",
    "Zobrazit vybrané produkty",
    "vypnuto",
    "položky",
    "Vyberte Plán předplatného",
    "Nejsou k dispozici žádné produkty",
    "Vyberte Možnosti",
    "Načíst další produkty",
    "Příprava balíčku...",
    "Přesměrování...",
    "Přidáno",
    "Přidat",
    "Recenze",
    "Vyberte Balíček produktů",
    "Množství",
    "jsi si jistý?",
    "Opravdu chcete vymazat všechny položky z košíku? Tuto akci nelze vrátit zpět...",
    "Jasný",
    "Zrušit",
    "Vymazat košík",
    "Odeberte {{boxSelectionDifference}} položek, abyste vybrali toto pole",
    "Odebrat tento produkt z {{stepName}}",
    "V tomto kroku přidejte alespoň {{conditionQuantity}} produktů",
    "Chcete-li pokračovat, přidejte maximálně {{conditionQuantity}} produktů",
    "V tomto kroku přidejte přesně {{conditionQuantity}} produktů",
    "V tomto kroku přidejte produkty v hodnotě alespoň {{conditionAmount}}",
    "V tomto kroku přidejte produkty v hodnotě maximálně {{conditionAmount}}",
    "V tomto kroku přidejte produkty v hodnotě {{conditionAmount}}",
    "V tomto kroku přidejte produkty o hmotnosti alespoň {{conditionWeight}}",
    "V tomto kroku přidejte produkty s maximální hmotností {{conditionWeight}}",
    "V tomto kroku přidejte produkty o hmotnosti {{conditionWeight}}",
    "V tomto kroku přidejte maximálně {{maxAllowedAddons}} doplňkových produktů",
    "Doplňkový produkt je v tomto kroku povinný",
    "Další nabídky k odemknutí",
    "Přidat do košíku",
    "Vyberte variantu",
    "Přidáno x{{allowedQuantity}}",
    "Přidejte +",
    "Vyberte {{quantityDifference}} položek",
    "Zobrazit položky v balíčku",
    "Vybrané produkty",
    "Mezisoučet",
    "Přidat balíček do košíku",
    "Předchozí",
    "Hotovo",
    "Přidávání balíčku...",
    "Balíček přidán",
    "Produkt",
    "Zobrazit všechny kroky",
    "Žádné další zásoby"
  ],
  "da": [
    "genstande",
    "Udsalgspris",
    "Du sparer",
    "Tilføj til boks",
    "Næste",
    "Tilføj til kurv",
    "Total",
    "Se udvalgte produkter",
    "slukket",
    "vare(r)",
    "Vælg Abonnementsplan",
    "Ingen tilgængelige produkter",
    "Vælg Indstillinger",
    "Indlæs flere produkter",
    "Forbereder pakke...",
    "Omdirigerer...",
    "Tilføjet",
    "Tilføje",
    "Gennemgå",
    "Vælg bundt produkter",
    "Mængde",
    "Er du sikker?",
    "Er du sikker på, at du vil slette alle varer fra din indkøbskurv? Denne handling kan ikke fortrydes...",
    "Klar",
    "Ophæve",
    "Ryd vogn",
    "Fjern {{boxSelectionDifference}} element(er) for at markere denne boks",
    "Fjern dette produkt fra {{stepName}}",
    "Tilføj mindst {{conditionQuantity}} produkter på dette trin",
    "Tilføj maksimalt {{conditionQuantity}} produkter for at fortsætte",
    "Tilføj nøjagtigt {{conditionQuantity}} produkter på dette trin",
    "Tilføj produkter til en værdi af mindst {{conditionAmount}} på dette trin",
    "Tilføj produkter til en værdi af maksimalt {{conditionAmount}} på dette trin",
    "Tilføj produkter til en værdi af {{conditionAmount}} på dette trin",
    "Tilføj produkter, der vejer mindst {{conditionWeight}} på dette trin",
    "Tilføj produkter, der maksimalt vejer {{conditionWeight}} på dette trin",
    "Tilføj produkter, der vejer {{conditionWeight}} på dette trin",
    "Tilføj maksimalt {{maxAllowedAddons}} tilføjelsesprodukter på dette trin",
    "Addon-produkt er obligatorisk på dette trin",
    "Yderligere tilbud skal låses op",
    "Tilføj til kurv",
    "Vælg variant",
    "Tilføjet x{{allowedQuantity}}",
    "Tilføj +",
    "Vælg {{quantityDifference}} varer",
    "Se pakkeelementer",
    "Udvalgte produkter",
    "Subtotal",
    "Tilføj pakke til kurv",
    "Prev",
    "Færdig",
    "Tilføjer pakke...",
    "Bunde tilføjet",
    "Produkt",
    "Vis alle trin",
    "Ikke mere lager"
  ],
  "nl": [
    "Artikelen",
    "Verkoopprijs",
    "Jij bespaart",
    "Toevoegen aan vak",
    "Volgende",
    "Voeg toe aan winkelwagen",
    "Totaal",
    "Bekijk geselecteerde producten",
    "uit",
    "artikel(en)",
    "Selecteer Abonnementsplan",
    "Geen producten beschikbaar",
    "Kies Opties",
    "Laad meer producten",
    "Bundel voorbereiden...",
    "Omleiden...",
    "Toegevoegd",
    "Toevoegen",
    "Beoordeling",
    "Selecteer Bundelproducten",
    "Hoeveelheid",
    "Weet je het zeker?",
    "Weet u zeker dat u alle artikelen uit uw winkelwagen wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt...",
    "Duidelijk",
    "Annuleren",
    "Winkelwagen leegmaken",
    "Verwijder {{boxSelectionDifference}} artikel(en) om dit vakje te selecteren",
    "Verwijder dit product uit {{stepName}}",
    "Voeg in deze stap minimaal {{conditionQuantity}} producten toe",
    "Voeg maximaal {{conditionQuantity}} producten toe om door te gaan",
    "Voeg in deze stap precies {{conditionQuantity}} producten toe",
    "Voeg in deze stap producten toe ter waarde van minimaal {{conditionAmount}}",
    "Voeg in deze stap producten toe ter waarde van maximaal {{conditionAmount}}",
    "Voeg in deze stap producten ter waarde van {{conditionAmount}} toe",
    "Voeg in deze stap producten toe die minimaal {{conditionWeight}} wegen",
    "Voeg in deze stap producten toe met een gewicht van maximaal {{conditionWeight}}",
    "Voeg in deze stap producten met een gewicht van {{conditionWeight}} toe",
    "Voeg bij deze stap maximaal {{maxAllowedAddons}} aanvullende producten toe",
    "Add-onproduct is verplicht bij deze stap",
    "Extra aanbiedingen om te ontgrendelen",
    "Voeg toe aan winkelwagen",
    "Variant selecteren",
    "x{{allowedQuantity}} toegevoegd",
    "Voeg + toe",
    "Selecteer {{quantityDifference}} Artikelen",
    "Bekijk bundelitems",
    "Geselecteerde producten",
    "Subtotaal",
    "Voeg bundel toe aan winkelwagen",
    "Vorige",
    "Klaar",
    "Bundel toevoegen...",
    "Bundel toegevoegd",
    "Product",
    "Toon alle stappen",
    "Geen voorraad meer"
  ],
  "et": [
    "Üksused",
    "Jaehind",
    "Sa säästad",
    "Lisa kasti",
    "Edasi",
    "Lisa ostukorvi",
    "Kokku",
    "Vaata valitud tooteid",
    "välja",
    "üksus(id)",
    "Valige Tellimisplaan",
    "Tooteid pole saadaval",
    "Valige Valikud",
    "Laadige rohkem tooteid",
    "Komplekti ettevalmistamine...",
    "Ümbersuunamine...",
    "Lisatud",
    "Lisa",
    "Ülevaade",
    "Valige Tootekomplektid",
    "Kogus",
    "Oled sa kindel?",
    "Kas olete kindel, et soovite kõik tooted ostukorvist tühjendada? Seda toimingut ei saa tagasi võtta...",
    "Selge",
    "Tühista",
    "Tühjenda ostukorvi",
    "Selle kasti valimiseks eemaldage {{boxSelectionDifference}} üksus(ed).",
    "Eemalda see toode numbrilt {{stepName}}",
    "Lisage selles etapis vähemalt {{conditionQuantity}} toodet",
    "Jätkamiseks lisage maksimaalselt {{conditionQuantity}} toodet",
    "Lisage selles etapis täpselt {{conditionQuantity}} toodet",
    "Lisage selles etapis tooteid, mille väärtus on vähemalt {{conditionAmount}}",
    "Lisage selles etapis tooteid maksimaalse väärtusega {{conditionAmount}}",
    "Lisa selles etapis tooteid väärtusega {{conditionAmount}}",
    "Lisage sellele sammule tooted, mis kaaluvad vähemalt {{conditionWeight}}",
    "Lisage sellele sammule tooted, mis kaaluvad maksimaalselt {{conditionWeight}}",
    "Lisage sellele sammule tooted kaaluga {{conditionWeight}}",
    "Lisage selles etapis maksimaalselt {{maxAllowedAddons}} lisatoodet",
    "Addoni toode on selles etapis kohustuslik",
    "Täiendavad pakkumised tuleb avada",
    "Lisa ostukorvi",
    "Vali variant",
    "Lisatud x{{allowedQuantity}}",
    "Lisa +",
    "Valige {{quantityDifference}} üksused",
    "Vaadake komplekti üksusi",
    "Valitud tooted",
    "Vahesumma",
    "Lisa komplekt ostukorvi",
    "Eelmine",
    "Valmis",
    "Komplekti lisamine...",
    "Komplekt lisatud",
    "Toode",
    "Kuva kõik sammud",
    "Laoseis pole enam"
  ],
  "fi": [
    "Tuotteet",
    "Vähittäismyyntihinta",
    "Säästät",
    "Lisää laatikkoon",
    "Seuraavaksi",
    "Lisää ostoskoriin",
    "Kokonais",
    "Katso valitut tuotteet",
    "pois",
    "tuote(t)",
    "Valitse tilaussuunnitelma",
    "Ei tuotteita saatavilla",
    "Valitse Asetukset",
    "Lataa lisää tuotteita",
    "Valmistellaan pakettia...",
    "Uudelleenohjataan...",
    "Lisätty",
    "Lisätä",
    "Arvostelu",
    "Valitse Bundle Products",
    "Määrä",
    "Oletko varma?",
    "Haluatko varmasti tyhjentää kaikki tuotteet ostoskoristasi? Tätä toimintoa ei voi kumota...",
    "Selkeä",
    "Peruuttaa",
    "Tyhjennä ostoskori",
    "Valitse tämä ruutu poistamalla {{boxSelectionDifference}} tuotetta",
    "Poista tämä tuote numerosta {{stepName}}",
    "Lisää vähintään {{conditionQuantity}} tuotetta tässä vaiheessa",
    "Lisää enintään {{conditionQuantity}} tuotetta jatkaaksesi",
    "Lisää tarkalleen {{conditionQuantity}} tuotetta tässä vaiheessa",
    "Lisää tähän vaiheeseen tuotteita, joiden arvo on vähintään {{conditionAmount}}",
    "Lisää tähän vaiheeseen tuotteita, joiden arvo on enintään {{conditionAmount}}",
    "Lisää tuotteita arvoltaan {{conditionAmount}} tässä vaiheessa",
    "Lisää tähän vaiheeseen tuotteita, jotka painavat vähintään {{conditionWeight}}",
    "Lisää tähän vaiheeseen tuotteita, joiden paino on enintään {{conditionWeight}}",
    "Lisää {{conditionWeight}} painoisia tuotteita tähän vaiheeseen",
    "Lisää enintään {{maxAllowedAddons}} lisätuotetta tässä vaiheessa",
    "Addon-tuote on pakollinen tässä vaiheessa",
    "Lisätarjouksia avataan",
    "Lisää ostoskoriin",
    "Valitse variantti",
    "Lisätty x{{allowedQuantity}}",
    "Lisää +",
    "Valitse {{quantityDifference}} tuotteet",
    "Näytä paketin tuotteet",
    "Valitut tuotteet",
    "Välisumma",
    "Lisää paketti ostoskoriin",
    "Ed",
    "Tehty",
    "Lisätään nippua...",
    "Paketti lisätty",
    "Tuote",
    "Näytä kaikki vaiheet",
    "Ei enää varastoa"
  ],
  "fr": [
    "Articles",
    "Prix ​​en détail",
    "Vous économisez",
    "Ajouter à la boîte",
    "Suivant",
    "Ajouter au panier",
    "Total",
    "Voir les produits sélectionnés",
    "désactivé",
    "articles)",
    "Sélectionnez le plan d'abonnement",
    "Aucun produit disponible",
    "Choisissez les options",
    "Charger plus de produits",
    "Préparation du paquet...",
    "Redirection...",
    "Ajouté",
    "Ajouter",
    "Revoir",
    "Sélectionnez les produits groupés",
    "Quantité",
    "Es-tu sûr?",
    "Etes-vous sûr de vouloir supprimer tous les articles de votre panier ? Cette action ne peut pas être annulée...",
    "Clair",
    "Annuler",
    "Vider le panier",
    "Supprimez {{boxSelectionDifference}} élément(s) pour sélectionner cette case",
    "Supprimer ce produit du {{stepName}}",
    "Ajoutez au moins {{conditionQuantity}} produits à cette étape",
    "Ajoutez un maximum de {{conditionQuantity}} produits pour continuer",
    "Ajoutez exactement {{conditionQuantity}} produits à cette étape",
    "Ajoutez des produits d'une valeur d'au moins {{conditionAmount}} à cette étape",
    "Ajoutez des produits d'une valeur maximale de {{conditionAmount}} à cette étape",
    "Ajoutez des produits d'une valeur de {{conditionAmount}} à cette étape",
    "Ajoutez des produits pesant au moins {{conditionWeight}} à cette étape",
    "Ajoutez des produits pesant au maximum {{conditionWeight}} à cette étape",
    "Ajoutez des produits pesant {{conditionWeight}} à cette étape",
    "Ajoutez un maximum de {{maxAllowedAddons}} produits complémentaires à cette étape",
    "Le produit complémentaire est obligatoire à cette étape",
    "Offres supplémentaires à débloquer",
    "Ajouter au panier",
    "Sélectionnez une variante",
    "x{{allowedQuantity}} ajouté",
    "Ajouter +",
    "Sélectionnez {{quantityDifference}} articles",
    "Afficher les articles du lot",
    "Produits sélectionnés",
    "Total",
    "Ajouter le lot au panier",
    "Précédent",
    "Fait",
    "Ajout d'un paquet...",
    "Offre groupée ajoutée",
    "Produit",
    "Afficher toutes les étapes",
    "Plus de stock"
  ],
  "ka": [
    "ნივთები",
    "საცალო ფასი",
    "თქვენ დაზოგავთ",
    "ყუთში დამატება",
    "შემდეგი",
    "კალათაში დამატება",
    "სულ",
    "შერჩეული პროდუქტების ნახვა",
    "გამორთულია",
    "ნივთ(ებ)ი",
    "აირჩიეთ სააბონენტო გეგმა",
    "პროდუქტები არ არის ხელმისაწვდომი",
    "აირჩიეთ ოფციები",
    "მეტი პროდუქტის ჩატვირთვა",
    "პაკეტის მომზადება...",
    "გადამისამართება...",
    "დამატებულია",
    "დამატება",
    "მიმოხილვა",
    "აირჩიეთ ნაკრები პროდუქტები",
    "რაოდენობა",
    "დარწმუნებული ხარ?",
    "დარწმუნებული ხართ, რომ გსურთ გაასუფთავოთ ყველა ელემენტი თქვენი კალათიდან? ამ მოქმედების გაუქმება შეუძლებელია...",
    "წმინდა",
    "გაუქმება",
    "გასუფთავება კალათა",
    "ამ ველის ასარჩევად ამოიღეთ {{boxSelectionDifference}} ელემენტ(ებ)ი",
    "ამოიღეთ ეს პროდუქტი {{stepName}}-დან",
    "დაამატეთ მინიმუმ {{conditionQuantity}} პროდუქტი ამ საფეხურზე",
    "გასაგრძელებლად დაამატეთ მაქსიმუმ {{conditionQuantity}} პროდუქტი",
    "დაამატეთ ზუსტად {{conditionQuantity}} პროდუქტი ამ ეტაპზე",
    "დაამატეთ მინიმუმ {{conditionAmount}} პროდუქცია ამ ეტაპზე",
    "დაამატეთ პროდუქტი, რომლის ღირებულებაა მაქსიმუმ {{conditionAmount}} ამ ეტაპზე",
    "დაამატეთ {{conditionAmount}} ღირებულების პროდუქტები ამ ეტაპზე",
    "დაამატეთ პროდუქტები, რომელთა წონაა მინიმუმ {{conditionWeight}} ამ ეტაპზე",
    "დაამატეთ პროდუქტები, რომელთა წონაა მაქსიმუმ {{conditionWeight}} ამ ეტაპზე",
    "დაამატეთ პროდუქტები {{conditionWeight}} მასით ამ საფეხურზე",
    "დაამატეთ მაქსიმუმ {{maxAllowedAddons}} დამატებითი პროდუქტი ამ ეტაპზე",
    "Addon პროდუქტი ამ ეტაპზე სავალდებულოა",
    "განბლოკვის დამატებითი შეთავაზებები",
    "კალათაში დამატება",
    "აირჩიეთ ვარიანტი",
    "დამატებულია x{{allowedQuantity}}",
    "დაამატეთ +",
    "აირჩიეთ {{quantityDifference}} ელემენტი",
    "პაკეტის ელემენტების ნახვა",
    "შერჩეული პროდუქტები",
    "სუბტოტალი",
    "პაკეტის დამატება კალათაში",
    "წინა",
    "შესრულებულია",
    "პაკეტის დამატება...",
    "დამატებულია პაკეტი",
    "პროდუქტი",
    "ყველა ნაბიჯის ჩვენება",
    "მეტი მარაგი"
  ],
  "de": [
    "Artikel",
    "Verkaufspreis",
    "Sie sparen",
    "Zur Box hinzufügen",
    "Nächste",
    "In den Warenkorb legen",
    "Gesamt",
    "Ausgewählte Produkte anzeigen",
    "aus",
    "Artikel)",
    "Wählen Sie Abonnementplan",
    "Keine Produkte verfügbar",
    "Wählen Sie Optionen",
    "Weitere Produkte laden",
    "Bundle wird vorbereitet...",
    "Weiterleitung...",
    "Hinzugefügt",
    "Hinzufügen",
    "Rezension",
    "Wählen Sie Bundle-Produkte aus",
    "Menge",
    "Bist du sicher?",
    "Sind Sie sicher, dass Sie alle Artikel aus Ihrem Warenkorb löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden...",
    "Klar",
    "Stornieren",
    "Warenkorb leeren",
    "Entfernen Sie {{boxSelectionDifference}} Artikel, um dieses Feld auszuwählen",
    "Entfernen Sie dieses Produkt von {{stepName}}",
    "Fügen Sie in diesem Schritt mindestens {{conditionQuantity}} Produkte hinzu",
    "Fügen Sie maximal {{conditionQuantity}} Produkte hinzu, um fortzufahren",
    "Fügen Sie in diesem Schritt genau {{conditionQuantity}} Produkte hinzu",
    "Fügen Sie in diesem Schritt Produkte im Wert von mindestens {{conditionAmount}} hinzu",
    "Fügen Sie in diesem Schritt Produkte im Wert von maximal {{conditionAmount}} hinzu",
    "Fügen Sie in diesem Schritt Produkte im Wert von {{conditionAmount}} hinzu",
    "Fügen Sie in diesem Schritt Produkte mit einem Gewicht von mindestens {{conditionWeight}} hinzu",
    "Fügen Sie in diesem Schritt Produkte mit einem Gewicht von maximal {{conditionWeight}} hinzu",
    "Fügen Sie in diesem Schritt Produkte mit einem Gewicht von {{conditionWeight}} hinzu",
    "Fügen Sie in diesem Schritt maximal {{maxAllowedAddons}} Add-on-Produkte hinzu",
    "Das Add-on-Produkt ist in diesem Schritt obligatorisch",
    "Zusätzliche Angebote zum Freischalten",
    "in den Warenkorb legen",
    "Variante auswählen",
    "x{{allowedQuantity}} hinzugefügt",
    "+ hinzufügen",
    "Wählen Sie {{quantityDifference}} Artikel",
    "Bundle-Artikel anzeigen",
    "Ausgewählte Produkte",
    "Zwischensumme",
    "Bundle zum Warenkorb hinzufügen",
    "Vorher",
    "Erledigt",
    "Bundle wird hinzugefügt...",
    "Bundle hinzugefügt",
    "Produkt",
    "Alle Schritte anzeigen",
    "Kein Lagerbestand mehr"
  ],
  "el": [
    "Είδη",
    "Τιμή λιανικής",
    "Αποταμιεύετε",
    "Προσθήκη στο πλαίσιο",
    "Επόμενος",
    "Προσθήκη στο καλάθι",
    "Σύνολο",
    "Προβολή επιλεγμένων προϊόντων",
    "μακριά από",
    "στοιχείο(α)",
    "Επιλέξτε Πρόγραμμα συνδρομής",
    "Δεν υπάρχουν διαθέσιμα προϊόντα",
    "Επιλέξτε Επιλογές",
    "Φόρτωση περισσότερων προϊόντων",
    "Προετοιμασία πακέτου...",
    "Ανακατεύθυνση...",
    "Προστέθηκε",
    "Προσθέτω",
    "Κριτική",
    "Επιλέξτε Πακέτα προϊόντων",
    "Ποσότητα",
    "Είσαι σίγουρος;",
    "Είστε βέβαιοι ότι θέλετε να διαγράψετε όλα τα στοιχεία από το καλάθι σας; Αυτή η ενέργεια δεν μπορεί να αναιρεθεί...",
    "Σαφής",
    "Ματαίωση",
    "Εκκαθάριση Καλαθιού",
    "Αφαιρέστε {{boxSelectionDifference}} αντικείμενο(α) για να επιλέξετε αυτό το πλαίσιο",
    "Αφαιρέστε αυτό το προϊόν από {{stepName}}",
    "Προσθέστε τουλάχιστον {{conditionQuantity}} προϊόντα σε αυτό το βήμα",
    "Προσθέστε έως και {{conditionQuantity}} προϊόντα για να συνεχίσετε",
    "Προσθέστε ακριβώς {{conditionQuantity}} προϊόντα σε αυτό το βήμα",
    "Προσθέστε προϊόντα αξίας τουλάχιστον {{conditionAmount}} σε αυτό το βήμα",
    "Προσθέστε προϊόντα με μέγιστη αξία {{conditionAmount}} σε αυτό το βήμα",
    "Προσθέστε προϊόντα αξίας {{conditionAmount}} σε αυτό το βήμα",
    "Προσθέστε προϊόντα με βάρος τουλάχιστον {{conditionWeight}} σε αυτό το βήμα",
    "Προσθέστε προϊόντα με μέγιστο βάρος {{conditionWeight}} σε αυτό το βήμα",
    "Προσθέστε προϊόντα με βάρος {{conditionWeight}} σε αυτό το βήμα",
    "Προσθέστε έως και {{maxAllowedAddons}} προϊόντα πρόσθετου σε αυτό το βήμα",
    "Το προϊόν Addon είναι υποχρεωτικό σε αυτό το βήμα",
    "Πρόσθετες προσφορές για ξεκλείδωμα",
    "Προσθήκη στο Καλάθι",
    "Επιλέξτε παραλλαγή",
    "Προστέθηκε x{{allowedQuantity}}",
    "Προσθήκη +",
    "Επιλέξτε {{quantityDifference}} είδη",
    "Προβολή στοιχείων δέσμης",
    "Επιλεγμένα Προϊόντα",
    "Υποσύνολο",
    "Προσθήκη πακέτου στο καλάθι",
    "Προηγ",
    "Γινώμενος",
    "Προσθήκη πακέτου...",
    "Προστέθηκε πακέτο",
    "Προϊόν",
    "Εμφάνιση όλων των βημάτων",
    "Όχι περισσότερα απόθεμα"
  ],
  "he": [
    "פריטים",
    "מחיר לצרכן",
    "אתה שומר",
    "הוסף לתיבה",
    "הַבָּא",
    "הוסף לעגלה",
    "סַך הַכֹּל",
    "הצג מוצרים נבחרים",
    "כבוי",
    "פריט(ים)",
    "בחר תוכנית מנוי",
    "אין מוצרים זמינים",
    "בחר אפשרויות",
    "טען עוד מוצרים",
    "מכין חבילה...",
    "מפנה מחדש...",
    "נוסף",
    "לְהוֹסִיף",
    "סְקִירָה",
    "בחר חבילת מוצרים",
    "כַּמוּת",
    "אתה בטוח?",
    "האם אתה בטוח שברצונך למחוק את כל הפריטים מהסל שלך? לא ניתן לבטל את הפעולה הזו...",
    "בָּרוּר",
    "לְבַטֵל",
    "נקה עגלה",
    "הסר {{boxSelectionDifference}} פריטים כדי לבחור בתיבה זו",
    "הסר מוצר זה מ-{{stepName}}",
    "הוסף לפחות {{conditionQuantity}} מוצרים בשלב זה",
    "הוסף מקסימום {{conditionQuantity}} מוצרים כדי להמשיך",
    "הוסף בדיוק {{conditionQuantity}} מוצרים בשלב זה",
    "הוסף מוצרים בשווי של לפחות {{conditionAmount}} בשלב זה",
    "הוסף מוצרים בשווי מקסימום של {{conditionAmount}} בשלב זה",
    "הוסף מוצרים בשווי {{conditionAmount}} בשלב זה",
    "הוסף מוצרים במשקל של לפחות {{conditionWeight}} בשלב זה",
    "הוסף מוצרים במשקל מקסימלי של {{conditionWeight}} בשלב זה",
    "הוסף מוצרים במשקל {{conditionWeight}} בשלב זה",
    "הוסף מקסימום {{maxAllowedAddons}} מוצרי תוסף בשלב זה",
    "מוצר Addon הוא חובה בשלב זה",
    "הצעות נוספות לביטול הנעילה",
    "הוסף לעגלה",
    "בחר גרסה",
    "נוסף x{{allowedQuantity}}",
    "הוסף +",
    "בחר {{quantityDifference}} פריטים",
    "הצג פריטי חבילה",
    "מוצרים נבחרים",
    "סכום משנה",
    "הוסף חבילה לעגלה",
    "הקודם",
    "נַעֲשָׂה",
    "מוסיף חבילה...",
    "צרור נוסף",
    "מוּצָר",
    "הצג את כל השלבים",
    "אין יותר מלאי"
  ],
  "hu": [
    "Tételek",
    "Kiskereskedelmi ár",
    "Megmented",
    "Hozzáadás a dobozhoz",
    "Következő",
    "Kosárba",
    "Teljes",
    "Tekintse meg a kiválasztott termékeket",
    "le",
    "elem(ek)",
    "Válassza az Előfizetési csomag lehetőséget",
    "Nincsenek elérhető termékek",
    "Válassza a Beállítások lehetőséget",
    "További termékek betöltése",
    "Csomag előkészítése...",
    "Átirányítás...",
    "Hozzáadva",
    "Hozzáadás",
    "Tekintse át",
    "Válassza ki a termékcsomagot",
    "Mennyiség",
    "Biztos vagy benne?",
    "Biztosan törölni szeretné az összes terméket a kosárból? Ez a művelet nem vonható vissza...",
    "Világos",
    "Mégse",
    "Tiszta kosár",
    "A mező kiválasztásához távolítsa el a {{boxSelectionDifference}} elemet",
    "Távolítsa el ezt a terméket a {{stepName}} számról",
    "Adjon hozzá legalább {{conditionQuantity}} terméket ebben a lépésben",
    "A folytatáshoz adjon hozzá legfeljebb {{conditionQuantity}} terméket",
    "Adjon hozzá pontosan {{conditionQuantity}} terméket ebben a lépésben",
    "Adjon hozzá legalább {{conditionAmount}} értékű termékeket ehhez a lépéshez",
    "Adjon hozzá legfeljebb {{conditionAmount}} értékű termékeket ebben a lépésben",
    "Adjon hozzá {{conditionAmount}} értékű termékeket ebben a lépésben",
    "Adjon hozzá legalább {{conditionWeight}} tömegű termékeket ehhez a lépéshez",
    "Adjon hozzá legfeljebb {{conditionWeight}} tömegű termékeket ebben a lépésben",
    "Adjon hozzá {{conditionWeight}} súlyú termékeket ebben a lépésben",
    "Ebben a lépésben legfeljebb {{maxAllowedAddons}} kiegészítő terméket adjon hozzá",
    "Az Addon termék kötelező ebben a lépésben",
    "További ajánlatok feloldása",
    "Kosárba",
    "Válasszon változatot",
    "Hozzáadott x{{allowedQuantity}}",
    "+ hozzáadása",
    "Válassza ki a {{quantityDifference}} tételeket",
    "Csomagelemek megtekintése",
    "Válogatott termékek",
    "Részösszeg",
    "Csomag hozzáadása a kosárhoz",
    "Előző",
    "Kész",
    "Csomag hozzáadása...",
    "Csomag hozzáadva",
    "Termék",
    "Az összes lépés megjelenítése",
    "Nincs több készlet"
  ],
  "id": [
    "Barang",
    "Harga eceran",
    "Anda Menyimpan",
    "Tambahkan Ke Kotak",
    "Berikutnya",
    "Tambahkan Ke Keranjang",
    "Total",
    "Lihat Produk Pilihan",
    "mati",
    "barang",
    "Pilih Paket Berlangganan",
    "Tidak Ada Produk yang Tersedia",
    "Pilih Opsi",
    "Muat Lebih Banyak Produk",
    "Mempersiapkan Bundel...",
    "Mengarahkan...",
    "Ditambahkan",
    "Menambahkan",
    "Tinjauan",
    "Pilih Produk Bundel",
    "Kuantitas",
    "Apa kamu yakin?",
    "Apakah Anda yakin ingin menghapus semua item dari keranjang Anda? Tindakan ini tidak dapat dibatalkan...",
    "Jernih",
    "Membatalkan",
    "Hapus Keranjang",
    "Hapus {{boxSelectionDifference}} item untuk memilih kotak ini",
    "Hapus Produk Ini Dari {{stepName}}",
    "Tambahkan setidaknya {{conditionQuantity}} produk pada langkah ini",
    "Tambahkan maksimal {{conditionQuantity}} produk untuk melanjutkan",
    "Tambahkan persis {{conditionQuantity}} produk pada langkah ini",
    "Tambahkan produk senilai minimal {{conditionAmount}} pada langkah ini",
    "Tambahkan produk senilai maksimum {{conditionAmount}} pada langkah ini",
    "Tambahkan produk senilai {{conditionAmount}} pada langkah ini",
    "Tambahkan produk dengan berat minimal {{conditionWeight}} pada langkah ini",
    "Tambahkan produk dengan berat maksimum {{conditionWeight}} pada langkah ini",
    "Tambahkan produk dengan berat {{conditionWeight}} pada langkah ini",
    "Tambahkan maksimal {{maxAllowedAddons}} produk tambahan pada langkah ini",
    "Produk Addon wajib ada pada langkah ini",
    "Penawaran tambahan untuk dibuka",
    "Tambahkan ke Keranjang",
    "Pilih varian",
    "Ditambahkan x{{allowedQuantity}}",
    "Tambahkan +",
    "Pilih {{quantityDifference}} Item",
    "Lihat Item Bundel",
    "Produk Pilihan",
    "Subtotal",
    "Tambahkan Paket ke Keranjang",
    "Sebelumnya",
    "Selesai",
    "Menambahkan Paket...",
    "Paket Ditambahkan",
    "Produk",
    "Tampilkan semua langkah",
    "Tidak Ada Stok Lagi"
  ],
  "it": [
    "Elementi",
    "Prezzo al dettaglio",
    "Risparmi",
    "Aggiungi alla casella",
    "Prossimo",
    "Aggiungi al carrello",
    "Totale",
    "Visualizza i prodotti selezionati",
    "spento",
    "elementi)",
    "Seleziona Piano di abbonamento",
    "Nessun prodotto disponibile",
    "Scegli Opzioni",
    "Carica più prodotti",
    "Preparazione del pacchetto...",
    "Reindirizzamento...",
    "Aggiunto",
    "Aggiungere",
    "Revisione",
    "Seleziona Prodotti in bundle",
    "Quantità",
    "Sei sicuro?",
    "Sei sicuro di voler eliminare tutti gli articoli dal carrello? Questa azione non può essere annullata...",
    "Chiaro",
    "Cancellare",
    "Cancella carrello",
    "Rimuovi {{boxSelectionDifference}} articolo/i per selezionare questa casella",
    "Rimuovi questo prodotto da {{stepName}}",
    "Aggiungi almeno {{conditionQuantity}} prodotti in questo passaggio",
    "Aggiungi un massimo di {{conditionQuantity}} prodotti per continuare",
    "Aggiungi esattamente {{conditionQuantity}} prodotti in questo passaggio",
    "Aggiungi prodotti del valore di almeno {{conditionAmount}} in questo passaggio",
    "Aggiungi prodotti per un valore massimo di {{conditionAmount}} in questo passaggio",
    "Aggiungi prodotti del valore di {{conditionAmount}} in questo passaggio",
    "Aggiungi i prodotti che pesano almeno {{conditionWeight}} in questo passaggio",
    "Aggiungi prodotti con un peso massimo di {{conditionWeight}} in questo passaggio",
    "Aggiungi i prodotti che pesano {{conditionWeight}} in questo passaggio",
    "Aggiungi un massimo di {{maxAllowedAddons}} prodotti aggiuntivi in ​​questo passaggio",
    "Il prodotto aggiuntivo è obbligatorio in questo passaggio",
    "Ulteriori offerte da sbloccare",
    "Aggiungi al carrello",
    "Seleziona variante",
    "Aggiunto x{{allowedQuantity}}",
    "Aggiungi +",
    "Seleziona {{quantityDifference}} Articoli",
    "Visualizza gli elementi del pacchetto",
    "Prodotti selezionati",
    "Totale parziale",
    "Aggiungi pacchetto al carrello",
    "Prec",
    "Fatto",
    "Aggiunta del pacchetto...",
    "Pacchetto aggiunto",
    "Prodotto",
    "Mostra tutti i passaggi",
    "Niente più scorte"
  ],
  "ja": [
    "アイテム",
    "小売価格",
    "保存します",
    "ボックスに追加",
    "次",
    "カートに追加",
    "合計",
    "選択した製品を表示",
    "オフ",
    "アイテム",
    "サブスクリプションプランを選択",
    "利用可能な製品はありません",
    "オプションの選択",
    "さらに製品をロードする",
    "バンドルを準備しています...",
    "リダイレクト中...",
    "追加した",
    "追加",
    "レビュー",
    "バンドル製品を選択してください",
    "量",
    "本気ですか？",
    "カートからすべてのアイテムをクリアしてもよろしいですか?この操作は元に戻せません...",
    "クリア",
    "キャンセル",
    "カートをクリアする",
    "このボックスを選択するには、{{boxSelectionDifference}} 個の項目を削除してください",
    "この製品を {{stepName}} から削除します",
    "このステップでは少なくとも {{conditionQuantity}} 製品を追加してください",
    "続行するには最大 {{conditionQuantity}} 個の製品を追加してください",
    "このステップでは、正確に {{conditionQuantity}} 製品を追加します。",
    "このステップでは、少なくとも {{conditionAmount}} 相当の製品を追加します。",
    "このステップでは、最大値 {{conditionAmount}} の製品を追加します。",
    "このステップで {{conditionAmount}} に相当する製品を追加します",
    "このステップでは、重量が少なくとも {{conditionWeight}} の製品を追加します。",
    "このステップでは、最大重量 {{conditionWeight}} の製品を追加します。",
    "このステップで重量 {{conditionWeight}} の製品を追加します",
    "このステップでは最大 {{maxAllowedAddons}} 個のアドオン製品を追加します。",
    "このステップではアドオン製品が必須です",
    "追加のオファーがロック解除されます",
    "カートに追加",
    "バリエーションの選択",
    "x{{allowedQuantity}}を追加しました",
    "+を追加",
    "{{quantityDifference}} アイテムを選択してください",
    "バンドルアイテムを表示",
    "厳選された製品",
    "小計",
    "バンドルをカートに追加",
    "前へ",
    "終わり",
    "バンドルを追加しています...",
    "バンドルが追加されました",
    "製品",
    "すべてのステップを表示",
    "もう在庫はありません"
  ],
  "ko": [
    "품목",
    "소매가",
    "당신은 저장",
    "상자에 추가",
    "다음",
    "장바구니에 추가",
    "총",
    "선택한 제품 보기",
    "끄다",
    "품목",
    "구독 계획 선택",
    "사용 가능한 제품이 없습니다.",
    "옵션을 선택하세요",
    "더 많은 제품 로드",
    "번들 준비 중...",
    "리디렉션 중...",
    "추가됨",
    "추가하다",
    "검토",
    "번들 제품 선택",
    "수량",
    "확실합니까?",
    "장바구니에서 모든 항목을 삭제하시겠습니까? 이 작업은 취소할 수 없습니다...",
    "분명한",
    "취소",
    "장바구니 지우기",
    "이 상자를 선택하려면 {{boxSelectionDifference}}개 항목을 제거하세요.",
    "{{stepName}}에서 이 제품을 제거하세요.",
    "이 단계에서 최소 {{conditionQuantity}}개의 제품을 추가하세요.",
    "계속하려면 최대 {{conditionQuantity}}개의 제품을 추가하세요.",
    "이 단계에서 정확히 {{conditionQuantity}}개의 제품을 추가하세요.",
    "이 단계에서 최소 {{conditionAmount}} 상당의 제품을 추가하세요.",
    "이 단계에서 최대 {{conditionAmount}} 상당의 제품을 추가하세요.",
    "이 단계에서 {{conditionAmount}} 상당의 제품을 추가하세요.",
    "이 단계에서 무게가 {{conditionWeight}} 이상인 제품을 추가하세요.",
    "이 단계에서 최대 무게가 {{conditionWeight}}인 제품을 추가하세요.",
    "이 단계에서 무게가 {{conditionWeight}}인 제품을 추가하세요.",
    "이 단계에서 최대 {{maxAllowedAddons}}개의 애드온 제품을 추가하세요.",
    "이 단계에서는 애드온 제품이 필수입니다.",
    "잠금 해제할 추가 혜택",
    "장바구니에 추가",
    "변형 선택",
    "x{{allowedQuantity}} 추가됨",
    "+ 추가",
    "{{quantityDifference}} 항목 선택",
    "번들 품목 보기",
    "선택된 제품",
    "소계",
    "장바구니에 번들 추가",
    "이전",
    "완료",
    "번들 추가 중...",
    "번들 추가됨",
    "제품",
    "모든 단계 표시",
    "더 이상 재고가 없습니다"
  ],
  "lv": [
    "Preces",
    "Mazumtirdzniecības cena",
    "Jūs ietaupāt",
    "Pievienot kastītei",
    "Tālāk",
    "Pievienot grozam",
    "Kopā",
    "Skatīt atlasītos produktus",
    "izslēgts",
    "prece(s)",
    "Atlasiet Abonēšanas plāns",
    "Nav pieejams neviens produkts",
    "Izvēlieties Opcijas",
    "Ielādēt vairāk produktu",
    "Notiek komplekta sagatavošana...",
    "Notiek novirzīšana...",
    "Pievienots",
    "Pievienot",
    "Pārskats",
    "Atlasiet produktu komplektu",
    "Daudzums",
    "Vai esat pārliecināts?",
    "Vai tiešām vēlaties dzēst visas preces no groza? Šo darbību nevar atsaukt...",
    "Skaidrs",
    "Atcelt",
    "Notīrīt grozu",
    "Noņemiet {{boxSelectionDifference}} vienumu(s), lai atlasītu šo lodziņu",
    "Noņemiet šo produktu no {{stepName}}",
    "Šajā darbībā pievienojiet vismaz {{conditionQuantity}} produktu",
    "Lai turpinātu, pievienojiet ne vairāk kā {{conditionQuantity}} produktu",
    "Šajā solī pievienojiet tieši {{conditionQuantity}} produktu",
    "Šajā darbībā pievienojiet produktus, kuru vērtība ir vismaz {{conditionAmount}}",
    "Šajā darbībā pievienojiet produktus, kuru vērtība nepārsniedz {{conditionAmount}}",
    "Šajā darbībā pievienojiet produktus {{conditionAmount}} vērtībā",
    "Šajā darbībā pievienojiet produktus, kas sver vismaz {{conditionWeight}}",
    "Šajā darbībā pievienojiet produktus, kuru maksimālais svars ir {{conditionWeight}}",
    "Šajā solī pievienojiet produktus, kas sver {{conditionWeight}}",
    "Šajā darbībā pievienojiet ne vairāk kā {{maxAllowedAddons}} papildinājuma produktus",
    "Šajā solī Addon produkts ir obligāts",
    "Papildu piedāvājumi tiks atbloķēti",
    "Pievienot grozam",
    "Izvēlieties variantu",
    "Pievienots x{{allowedQuantity}}",
    "Pievienojiet +",
    "Izvēlieties {{quantityDifference}} preces",
    "Skatīt komplekta vienumus",
    "Izvēlētie produkti",
    "Starpsumma",
    "Pievienot komplektu grozam",
    "Iepriekšējā",
    "Gatavs",
    "Notiek komplekta pievienošana...",
    "Komplekts pievienots",
    "Produkts",
    "Rādīt visas darbības",
    "Vairāk nav krājumu"
  ],
  "lt": [
    "Daiktai",
    "Mažmeninė kaina",
    "Jūs sutaupote",
    "Pridėti į dėžutę",
    "Kitas",
    "Pridėti į krepšelį",
    "Iš viso",
    "Peržiūrėkite pasirinktus produktus",
    "išjungti",
    "prekė (-ės)",
    "Pasirinkite Prenumeratos planą",
    "Produktų nėra",
    "Pasirinkite Parinktys",
    "Įkelti daugiau produktų",
    "Ruošiamas rinkinys...",
    "Peradresuojama...",
    "Pridėta",
    "Pridėti",
    "Apžvalga",
    "Pasirinkite produktų paketą",
    "Kiekis",
    "Ar esi tikras?",
    "Ar tikrai norite išvalyti visas prekes iš krepšelio? Šio veiksmo anuliuoti negalima...",
    "Aišku",
    "Atšaukti",
    "Išvalyti krepšelį",
    "Pašalinkite {{boxSelectionDifference}} prekę (-es), kad pasirinktumėte šį laukelį",
    "Pašalinti šį produktą iš {{stepName}}",
    "Šiame žingsnyje pridėkite bent {{conditionQuantity}} produktą",
    "Jei norite tęsti, pridėkite daugiausia {{conditionQuantity}} produkto",
    "Šiame žingsnyje pridėkite tiksliai {{conditionQuantity}} produktų",
    "Šiame žingsnyje pridėkite produktų, kurių vertė yra bent {{conditionAmount}}",
    "Šiame žingsnyje pridėkite produktų, kurių vertė neviršija {{conditionAmount}}",
    "Šiame žingsnyje pridėkite produktų, kurių vertė {{conditionAmount}}",
    "Šiame žingsnyje pridėkite produktus, sveriančius bent {{conditionWeight}}",
    "Šiame žingsnyje pridėkite produktus, sveriančius ne daugiau kaip {{conditionWeight}}",
    "Šiame žingsnyje pridėkite produktus, sveriančius {{conditionWeight}}",
    "Atlikdami šį veiksmą pridėkite daugiausia {{maxAllowedAddons}} papildomo produkto",
    "Šiame žingsnyje „Addon“ produktas yra privalomas",
    "Atrakinami papildomi pasiūlymai",
    "Pridėti į krepšelį",
    "Pasirinkite variantą",
    "Pridėta x{{allowedQuantity}}",
    "Pridėti +",
    "Pasirinkite {{quantityDifference}} prekes",
    "Peržiūrėti paketo elementus",
    "Atrinkti produktai",
    "Tarpinė suma",
    "Pridėti paketą į krepšelį",
    "Ankstesnis",
    "Atlikta",
    "Pridedamas rinkinys...",
    "Komplektas pridėtas",
    "Produktas",
    "Rodyti visus veiksmus",
    "Daugiau atsargų nėra"
  ],
  "nb": [
    "Varer",
    "Utsalgspris",
    "Du sparer",
    "Legg til i boks",
    "Neste",
    "Legg i handlekurven",
    "Total",
    "Se utvalgte produkter",
    "av",
    "vare(r)",
    "Velg Abonnementsplan",
    "Ingen produkter tilgjengelig",
    "Velg Alternativer",
    "Last inn flere produkter",
    "Forbereder pakke...",
    "Omdirigerer...",
    "Lagt til",
    "Legge til",
    "Gjennomgå",
    "Velg pakke produkter",
    "Mengde",
    "Er du sikker?",
    "Er du sikker på at du vil slette alle varer fra handlekurven? Denne handlingen kan ikke angres...",
    "Klar",
    "Kansellere",
    "Tøm handlekurven",
    "Fjern {{boxSelectionDifference}} element(er) for å velge denne boksen",
    "Fjern dette produktet fra {{stepName}}",
    "Legg til minst {{conditionQuantity}} produkter på dette trinnet",
    "Legg til maksimalt {{conditionQuantity}} produkter for å fortsette",
    "Legg til nøyaktig {{conditionQuantity}} produkter på dette trinnet",
    "Legg til produkter verdt minst {{conditionAmount}} på dette trinnet",
    "Legg til produkter verdt maksimalt {{conditionAmount}} på dette trinnet",
    "Legg til produkter verdt {{conditionAmount}} på dette trinnet",
    "Legg til produkter som veier minst {{conditionWeight}} på dette trinnet",
    "Legg til produkter som veier maksimalt {{conditionWeight}} på dette trinnet",
    "Legg til produkter som veier {{conditionWeight}} på dette trinnet",
    "Legg til maksimalt {{maxAllowedAddons}} tilleggsprodukter på dette trinnet",
    "Tilleggsprodukt er obligatorisk på dette trinnet",
    "Ytterligere tilbud som skal låses opp",
    "Legg i handlekurven",
    "Velg variant",
    "Lagt til x{{allowedQuantity}}",
    "Legg til +",
    "Velg {{quantityDifference}} varer",
    "Se pakkeelementer",
    "Utvalgte produkter",
    "Delsum",
    "Legg pakken i handlekurven",
    "Forrige",
    "Ferdig",
    "Legger til pakke ...",
    "Pakke lagt til",
    "Produkt",
    "Vis alle trinn",
    "Ikke mer lager"
  ],
  "pl": [
    "Rzeczy",
    "Cena detaliczna",
    "Oszczędzasz",
    "Dodaj do pola",
    "Następny",
    "Dodaj do koszyka",
    "Całkowity",
    "Zobacz wybrane produkty",
    "wyłączony",
    "rzeczy)",
    "Wybierz Plan subskrypcji",
    "Brak dostępnych produktów",
    "Wybierz Opcje",
    "Załaduj więcej produktów",
    "Przygotowywanie pakietu...",
    "Przekierowywanie...",
    "W dodatku",
    "Dodać",
    "Recenzja",
    "Wybierz Produkty w pakiecie",
    "Ilość",
    "Czy jesteś pewien?",
    "Czy na pewno chcesz usunąć wszystkie produkty ze swojego koszyka? Tej akcji nie można cofnąć...",
    "Jasne",
    "Anulować",
    "Wyczyść koszyk",
    "Usuń {{boxSelectionDifference}} elementów, aby zaznaczyć to pole",
    "Usuń ten produkt z {{stepName}}",
    "Dodaj co najmniej {{conditionQuantity}} produktów na tym etapie",
    "Aby kontynuować, dodaj maksymalnie {{conditionQuantity}} produktów",
    "Dodaj dokładnie {{conditionQuantity}} produktów na tym etapie",
    "Na tym etapie dodaj produkty o wartości co najmniej {{conditionAmount}}",
    "Na tym etapie dodaj produkty o maksymalnej wartości {{conditionAmount}}",
    "Na tym etapie dodaj produkty o wartości {{conditionAmount}}",
    "Na tym etapie dodaj produkty o wadze co najmniej {{conditionWeight}}",
    "Na tym etapie dodaj produkty o maksymalnej wadze {{conditionWeight}}",
    "Na tym etapie dodaj produkty o wadze {{conditionWeight}}",
    "Na tym etapie dodaj maksymalnie {{maxAllowedAddons}} produktów dodatkowych",
    "Produkt Addon jest obowiązkowy na tym etapie",
    "Dodatkowe oferty do odblokowania",
    "Dodaj do koszyka",
    "Wybierz wariant",
    "Dodano x{{allowedQuantity}}",
    "Dodaj +",
    "Wybierz elementy {{quantityDifference}}",
    "Zobacz elementy pakietu",
    "Wybrane produkty",
    "Suma częściowa",
    "Dodaj pakiet do koszyka",
    "Poprzednia",
    "Zrobione",
    "Dodawanie pakietu...",
    "Dodano pakiet",
    "Produkt",
    "Pokaż wszystkie kroki",
    "Nigdy więcej zapasów"
  ],
  "pt-BR": [
    "Unid",
    "Preço de varejo",
    "Você salva",
    "Adicionar à caixa",
    "Próximo",
    "Adicionar ao carrinho",
    "Total",
    "Ver produtos selecionados",
    "desligado",
    "Unid)",
    "Selecione o plano de assinatura",
    "Nenhum produto disponível",
    "Escolha opções",
    "Carregar mais produtos",
    "Preparando pacote...",
    "Redirecionando...",
    "Adicionado",
    "Adicionar",
    "Análise",
    "Selecione Pacote de Produtos",
    "Quantidade",
    "Tem certeza?",
    "Tem certeza de que deseja limpar todos os itens do seu carrinho? Esta ação não pode ser desfeita...",
    "Claro",
    "Cancelar",
    "Limpar carrinho",
    "Remova {{boxSelectionDifference}} itens para selecionar esta caixa",
    "Remova este produto de {{stepName}}",
    "Adicione pelo menos {{conditionQuantity}} produtos nesta etapa",
    "Adicione no máximo {{conditionQuantity}} produtos para continuar",
    "Adicione exatamente {{conditionQuantity}} produtos nesta etapa",
    "Adicione produtos no valor de pelo menos {{conditionAmount}} nesta etapa",
    "Adicione produtos com valor máximo de {{conditionAmount}} nesta etapa",
    "Adicione produtos no valor de {{conditionAmount}} nesta etapa",
    "Adicione produtos com peso mínimo de {{conditionWeight}} nesta etapa",
    "Adicione produtos com peso máximo de {{conditionWeight}} nesta etapa",
    "Adicione produtos com peso {{conditionWeight}} nesta etapa",
    "Adicione no máximo {{maxAllowedAddons}} produtos complementares nesta etapa",
    "O produto complementar é obrigatório nesta etapa",
    "Ofertas adicionais a serem desbloqueadas",
    "adicionar ao carrinho",
    "Selecione a variante",
    "Adicionado x{{allowedQuantity}}",
    "Adicionar +",
    "Selecione {{quantityDifference}} itens",
    "Ver itens do pacote",
    "Produtos Selecionados",
    "Subtotal",
    "Adicionar pacote ao carrinho",
    "Anterior",
    "Feito",
    "Adicionando pacote...",
    "Pacote adicionado",
    "Produto",
    "Mostrar todas as etapas",
    "Não há mais estoque"
  ],
  "pt-PT": [
    "Artigos",
    "Preço de venda ao público",
    "Você salva",
    "Adicionar à caixa",
    "Seguinte",
    "Adicionar ao carrinho",
    "Total",
    "Ver produtos selecionados",
    "desligado",
    "artigos)",
    "Selecione o plano de subscrição",
    "Nenhum produto disponível",
    "Escolha opções",
    "Carregar mais produtos",
    "Preparar pacote...",
    "Redireccionando...",
    "Adicionado",
    "Adicionar",
    "Revisão",
    "Selecione Pacote de Produtos",
    "Quantidade",
    "Tem a certeza?",
    "Tem a certeza de que pretende limpar todos os artigos do seu carrinho? Esta ação não pode ser desfeita...",
    "Claro",
    "Cancelar",
    "Limpar carrinho",
    "Remova {{boxSelectionDifference}} artigos para selecionar esta caixa",
    "Remover este produto de {{stepName}}",
    "Adicione pelo menos {{conditionQuantity}} produtos nesta fase",
    "Adicione no máximo {{conditionQuantity}} produtos para continuar",
    "Adicione exatamente {{conditionQuantity}} produtos nesta etapa",
    "Adicione produtos no valor de pelo menos {{conditionAmount}} nesta fase",
    "Adicionar produtos com o valor máximo de {{conditionAmount}} nesta etapa",
    "Adicione produtos no valor de {{conditionAmount}} nesta etapa",
    "Adicione produtos com um peso mínimo de {{conditionWeight}} nesta etapa",
    "Adicione produtos com o peso máximo de {{conditionWeight}} nesta etapa",
    "Adicione produtos com o peso {{conditionWeight}} nesta etapa",
    "Adicione no máximo {{maxAllowedAddons}} produtos complementares nesta etapa",
    "O produto complementar é obrigatório nesta fase",
    "Ofertas adicionais a desbloquear",
    "adicionar ao carrinho",
    "Selecione a variante",
    "Adicionado x{{allowedQuantity}}",
    "Adicionar +",
    "Selecione {{quantityDifference}} artigos",
    "Ver artigos do pacote",
    "Produtos Selecionados",
    "Subtotal",
    "Adicionar pacote ao carrinho",
    "Anterior",
    "Concluído",
    "Adicionando pacote...",
    "Pacote adicionado",
    "Produto",
    "Mostrar todas as etapas",
    "Não há mais stock"
  ],
  "ro": [
    "Articole",
    "Prețul de vânzare cu amănuntul",
    "Salvați",
    "Adăugați în casetă",
    "Următorul",
    "Adaugă in coş",
    "Total",
    "Vizualizați produsele selectate",
    "oprit",
    "articol(e)",
    "Selectați Plan de abonament",
    "Nu există produse disponibile",
    "Alegeți Opțiuni",
    "Încărcați mai multe produse",
    "Se pregătește pachetul...",
    "Se redirecționează...",
    "Adăugat",
    "Adăuga",
    "Recenzie",
    "Selectați Bundle Products",
    "Cantitate",
    "esti sigur?",
    "Sigur doriți să ștergeți toate articolele din coș? Această acțiune nu poate fi anulată...",
    "Clar",
    "Anula",
    "Ștergeți coșul",
    "Eliminați {{boxSelectionDifference}} articol(e) pentru a selecta această casetă",
    "Eliminați acest produs de la {{stepName}}",
    "Adăugați cel puțin {{conditionQuantity}} produse la acest pas",
    "Adăugați maximum {{conditionQuantity}} produse pentru a continua",
    "Adaugă exact {{conditionQuantity}} produse la acest pas",
    "Adăugați produse în valoare de cel puțin {{conditionAmount}} la acest pas",
    "Adăugați produse în valoare maximă de {{conditionAmount}} la acest pas",
    "Adăugați produse în valoare de {{conditionAmount}} la acest pas",
    "Adăugați produse care cântăresc cel puțin {{conditionWeight}} la acest pas",
    "Adăugați produse cu o greutate maximă de {{conditionWeight}} la acest pas",
    "Adăugați produse cu o greutate de {{conditionWeight}} la acest pas",
    "Adăugați maximum {{maxAllowedAddons}} produse addon la acest pas",
    "Produsul suplimentar este obligatoriu la acest pas",
    "Oferte suplimentare de deblocat",
    "Adaugă in coş",
    "Selectați varianta",
    "S-a adăugat x{{allowedQuantity}}",
    "Adăugați +",
    "Selectați {{quantityDifference}} Articole",
    "Vedeți articolele pachetului",
    "Produse Selectate",
    "Subtotal",
    "Adăugați pachetul în coș",
    "Prev",
    "Făcut",
    "Se adaugă pachetul...",
    "Pachet adăugat",
    "Produs",
    "Afișați toți pașii",
    "Nu mai sunt stocuri"
  ],
  "ru": [
    "Предметы",
    "Розничная цена",
    "Вы экономите",
    "Добавить в коробку",
    "Следующий",
    "Добавить в корзину",
    "Общий",
    "Посмотреть выбранные продукты",
    "выключенный",
    "предметы)",
    "Выберите план подписки",
    "Нет доступных продуктов",
    "Выберите параметры",
    "Загрузить больше продуктов",
    "Подготовка пакета...",
    "Перенаправление...",
    "Добавлен",
    "Добавлять",
    "Обзор",
    "Выберите продукты пакета",
    "Количество",
    "Вы уверены?",
    "Вы уверены, что хотите удалить все товары из корзины? Это действие невозможно отменить...",
    "Прозрачный",
    "Отмена",
    "Очистить корзину",
    "Удалите {{boxSelectionDifference}} элемент(ов), чтобы установить этот флажок.",
    "Удалить этот продукт из {{stepName}}",
    "Добавьте на этот шаг не менее {{conditionQuantity}} товаров.",
    "Добавьте максимум {{conditionQuantity}} товаров, чтобы продолжить.",
    "На этом шаге добавьте ровно {{conditionQuantity}} товаров.",
    "На этом шаге добавьте товары на сумму не менее {{conditionAmount}}.",
    "На этом шаге добавьте товары на сумму не более {{conditionAmount}}.",
    "На этом шаге добавьте товары на сумму {{conditionAmount}}.",
    "На этом шаге добавьте товары весом не менее {{conditionWeight}}.",
    "На этом шаге добавьте товары весом не более {{conditionWeight}}.",
    "На этом шаге добавьте товары весом {{conditionWeight}}.",
    "На этом этапе добавьте максимум {{maxAllowedAddons}} дополнительных продуктов.",
    "Дополнительный продукт является обязательным на этом этапе.",
    "Дополнительные предложения, которые нужно разблокировать",
    "добавить в корзину",
    "Выберите вариант",
    "Добавлен x{{allowedQuantity}}",
    "Добавить +",
    "Выберите {{quantityDifference}} товаров",
    "Посмотреть элементы пакета",
    "Выбранные продукты",
    "Итого",
    "Добавить комплект в корзину",
    "Предыдущий",
    "Сделанный",
    "Добавление пакета...",
    "Пакет добавлен",
    "Продукт",
    "Показать все шаги",
    "Нет больше акций"
  ],
  "sr": [
    "Предмети",
    "Ретаил Прице",
    "Иоу Саве",
    "Додај у кутију",
    "Следеће",
    "Додај у корпу",
    "Укупно",
    "Погледајте изабране производе",
    "искључено",
    "ставка(е)",
    "Изаберите План претплате",
    "Нема доступних производа",
    "Изаберите Опције",
    "Учитајте више производа",
    "Припрема пакета...",
    "Преусмеравање...",
    "Додато",
    "Додај",
    "Преглед",
    "Изаберите Пакет производа",
    "Количина",
    "Јесте ли сигурни?",
    "Да ли сте сигурни да желите да обришете све артикле из корпе? Ова радња се не може опозвати...",
    "Јасно",
    "Откажи",
    "Цлеар Царт",
    "Уклоните {{boxSelectionDifference}} ставку(е) да бисте изабрали овај оквир",
    "Уклоните овај производ са {{stepName}}",
    "Додајте најмање {{conditionQuantity}} производа на овом кораку",
    "Додајте највише {{conditionQuantity}} производа да бисте наставили",
    "Додајте тачно {{conditionQuantity}} производа на овом кораку",
    "Додајте производе у вредности од најмање {{conditionAmount}} на овом кораку",
    "Додајте производе максималне вредности {{conditionAmount}} на овом кораку",
    "Додајте производе у вредности од {{conditionAmount}} на овом кораку",
    "Додајте производе тежине најмање {{conditionWeight}} на овом кораку",
    "Додајте производе максималне тежине {{conditionWeight}} на овом кораку",
    "Додајте производе тежине {{conditionWeight}} на овом кораку",
    "Додајте највише {{maxAllowedAddons}} аддон производа на овом кораку",
    "Додатни производ је обавезан на овом кораку",
    "Додатне понуде које треба откључати",
    "Додај у корпу",
    "Изаберите варијанту",
    "Додато к{{allowedQuantity}}",
    "Додај +",
    "Изаберите {{quantityDifference}} Ставке",
    "Прикажи ставке пакета",
    "Одабрани производи",
    "Међузбир",
    "Додајте пакет у корпу",
    "Прев",
    "Готово",
    "Додавање пакета...",
    "Бундле Аддед",
    "Производ",
    "Прикажи све кораке",
    "Нема више залиха"
  ],
  "sk-SK": [
    "Položky",
    "Maloobchodná cena",
    "Ušetríte",
    "Pridať do schránky",
    "Ďalej",
    "Pridať do košíka",
    "Celkom",
    "Zobraziť vybrané produkty",
    "vypnuté",
    "položky",
    "Vyberte Plán predplatného",
    "Nie sú dostupné žiadne produkty",
    "Vyberte Možnosti",
    "Načítať viac produktov",
    "Pripravuje sa balík...",
    "Prebieha presmerovanie...",
    "Pridané",
    "Pridať",
    "recenzia",
    "Vyberte balík produktov",
    "Množstvo",
    "si si istý?",
    "Naozaj chcete vymazať všetky položky z košíka? Táto akcia sa nedá vrátiť späť...",
    "Jasné",
    "Zrušiť",
    "Vymazať košík",
    "Odstrániť {{boxSelectionDifference}} položiek, aby ste vybrali toto políčko",
    "Odstrániť tento produkt z čísla {{stepName}}",
    "V tomto kroku pridajte aspoň {{conditionQuantity}} produktov",
    "Ak chcete pokračovať, pridajte maximálne {{conditionQuantity}} produktov",
    "V tomto kroku pridajte presne {{conditionQuantity}} produktov",
    "V tomto kroku pridajte produkty v hodnote aspoň {{conditionAmount}}",
    "V tomto kroku pridajte produkty v hodnote maximálne {{conditionAmount}}",
    "V tomto kroku pridajte produkty v hodnote {{conditionAmount}}",
    "V tomto kroku pridajte produkty s hmotnosťou aspoň {{conditionWeight}}",
    "V tomto kroku pridajte produkty s maximálnou hmotnosťou {{conditionWeight}}",
    "V tomto kroku pridajte produkty s hmotnosťou {{conditionWeight}}",
    "V tomto kroku pridajte maximálne {{maxAllowedAddons}} doplnkových produktov",
    "Doplnkový produkt je v tomto kroku povinný",
    "Ďalšie ponuky na odomknutie",
    "Pridať do košíka",
    "Vyberte variant",
    "Pridané x{{allowedQuantity}}",
    "Pridajte +",
    "Vyberte {{quantityDifference}} položiek",
    "Zobraziť položky balíka",
    "Vybrané produkty",
    "Medzisúčet",
    "Pridať balík do košíka",
    "Predch",
    "Hotovo",
    "Pridáva sa balík...",
    "Balík pridaný",
    "Produkt",
    "Zobraziť všetky kroky",
    "Žiadne ďalšie zásoby"
  ],
  "sl-SI": [
    "Predmeti",
    "Maloprodajna cena",
    "Vi prihranite",
    "Dodaj v polje",
    "Naprej",
    "Dodaj v košarico",
    "Skupaj",
    "Oglejte si izbrane izdelke",
    "izklopljeno",
    "predmet(i)",
    "Izberite Naročniški načrt",
    "Ni izdelkov na voljo",
    "Izberite Možnosti",
    "Naloži več izdelkov",
    "Priprava paketa ...",
    "Preusmerjanje ...",
    "Dodano",
    "Dodaj",
    "Pregled",
    "Izberite Paket izdelkov",
    "Količina",
    "Ste prepričani?",
    "Ali ste prepričani, da želite počistiti vse predmete iz košarice? Tega dejanja ni mogoče razveljaviti ...",
    "jasno",
    "Prekliči",
    "Počisti voziček",
    "Odstranite {{boxSelectionDifference}} element(ov), da izberete to polje",
    "Odstranite ta izdelek iz {{stepName}}",
    "V tem koraku dodajte vsaj {{conditionQuantity}} izdelkov",
    "Za nadaljevanje dodajte največ {{conditionQuantity}} izdelkov",
    "V tem koraku dodajte natanko {{conditionQuantity}} izdelkov",
    "Na tem koraku dodajte izdelke v vrednosti najmanj {{conditionAmount}}",
    "V tem koraku dodajte izdelke v vrednosti največ {{conditionAmount}}",
    "Na tem koraku dodajte izdelke v vrednosti {{conditionAmount}}",
    "V tem koraku dodajte izdelke, ki tehtajo najmanj {{conditionWeight}}",
    "V tem koraku dodajte izdelke, ki tehtajo največ {{conditionWeight}}",
    "Na tem koraku dodajte izdelke s težo {{conditionWeight}}",
    "V tem koraku dodajte največ {{maxAllowedAddons}} dodatnih izdelkov",
    "Dodatni izdelek je obvezen v tem koraku",
    "Dodatne ponudbe, ki jih je treba odkleniti",
    "Dodaj v košarico",
    "Izberite varianto",
    "Dodano x{{allowedQuantity}}",
    "Dodajte +",
    "Izberite elemente {{quantityDifference}}",
    "Oglejte si elemente paketa",
    "Izbrani izdelki",
    "Vmesni seštevek",
    "Dodajte paket v košarico",
    "Prejšnji",
    "Končano",
    "Dodajanje svežnja ...",
    "Paket dodan",
    "Izdelek",
    "Pokaži vse korake",
    "Nič več zaloge"
  ],
  "es": [
    "Elementos",
    "Precio al por menor",
    "Ahorras",
    "Añadir al cuadro",
    "Próximo",
    "Añadir a la cesta",
    "Total",
    "Ver productos seleccionados",
    "apagado",
    "elementos)",
    "Seleccionar plan de suscripción",
    "No hay productos disponibles",
    "Elija opciones",
    "Cargar más productos",
    "Preparando paquete...",
    "Redirigiendo...",
    "Agregado",
    "Agregar",
    "Revisar",
    "Seleccionar paquetes de productos",
    "Cantidad",
    "¿Está seguro?",
    "¿Está seguro de que desea borrar todos los artículos de su carrito? Esta acción no se puede deshacer...",
    "Claro",
    "Cancelar",
    "Borrar carrito",
    "Elimine {{boxSelectionDifference}} elementos para seleccionar esta casilla",
    "Eliminar este producto de {{stepName}}",
    "Agregue al menos {{conditionQuantity}} productos en este paso",
    "Añade un máximo de {{conditionQuantity}} productos para continuar",
    "Agregue exactamente {{conditionQuantity}} productos en este paso",
    "Agregue productos con un valor mínimo de {{conditionAmount}} en este paso",
    "Agregue productos con un valor máximo de {{conditionAmount}} en este paso",
    "Agregue productos por valor de {{conditionAmount}} en este paso",
    "Agregue productos que pesen al menos {{conditionWeight}} en este paso",
    "Agregue productos con un peso máximo de {{conditionWeight}} en este paso",
    "Agregue productos que pesen {{conditionWeight}} en este paso",
    "Agregue un máximo de {{maxAllowedAddons}} productos complementarios en este paso",
    "El producto adicional es obligatorio en este paso",
    "Ofertas adicionales por desbloquear",
    "añadir a la cesta",
    "Seleccionar variante",
    "Añadido x{{allowedQuantity}}",
    "Añadir +",
    "Seleccione {{quantityDifference}} artículos",
    "Ver artículos del paquete",
    "Productos seleccionados",
    "Total parcial",
    "Agregar paquete al carrito",
    "Anterior",
    "Hecho",
    "Agregando paquete...",
    "Paquete agregado",
    "Producto",
    "Mostrar todos los pasos",
    "No más existencias"
  ],
  "sv": [
    "Föremål",
    "Butikspris",
    "Du sparar",
    "Lägg till i box",
    "Nästa",
    "Lägg till i varukorgen",
    "Total",
    "Se utvalda produkter",
    "av",
    "föremål",
    "Välj Prenumerationsplan",
    "Inga produkter tillgängliga",
    "Välj Alternativ",
    "Ladda fler produkter",
    "Förbereder paket...",
    "Omdirigerar...",
    "Tillagd",
    "Tillägga",
    "Recension",
    "Välj paketprodukter",
    "Kvantitet",
    "Är du säker?",
    "Är du säker på att du vill ta bort alla varor från din kundvagn? Den här åtgärden kan inte ångras...",
    "Rensa",
    "Avboka",
    "Rensa vagnen",
    "Ta bort {{boxSelectionDifference}} objekt för att markera den här rutan",
    "Ta bort den här produkten från {{stepName}}",
    "Lägg till minst {{conditionQuantity}} produkter i detta steg",
    "Lägg till maximalt {{conditionQuantity}} produkter för att fortsätta",
    "Lägg till exakt {{conditionQuantity}} produkter i detta steg",
    "Lägg till produkter värda minst {{conditionAmount}} i detta steg",
    "Lägg till produkter värda högst {{conditionAmount}} i detta steg",
    "Lägg till produkter värda {{conditionAmount}} i detta steg",
    "Lägg till produkter som väger minst {{conditionWeight}} i detta steg",
    "Lägg till produkter som väger högst {{conditionWeight}} i detta steg",
    "Lägg till produkter som väger {{conditionWeight}} i detta steg",
    "Lägg till maximalt {{maxAllowedAddons}} tilläggsprodukter i det här steget",
    "Tilläggsprodukt är obligatorisk i detta steg",
    "Ytterligare erbjudanden som ska låsas upp",
    "Lägg till i varukorgen",
    "Välj variant",
    "Lade till x{{allowedQuantity}}",
    "Lägg till +",
    "Välj {{quantityDifference}} artiklar",
    "Visa paketföremål",
    "Utvalda produkter",
    "Delsumma",
    "Lägg till paket i varukorgen",
    "Föreg",
    "Gjort",
    "Lägger till paket...",
    "Paket har lagts till",
    "Produkt",
    "Visa alla steg",
    "Inget mer lager"
  ],
  "th": [
    "รายการ",
    "ราคาขายปลีก",
    "คุณบันทึก",
    "เพิ่มลงในกล่อง",
    "ต่อไป",
    "เพิ่มลงตะกร้า",
    "ทั้งหมด",
    "ดูผลิตภัณฑ์ที่เลือก",
    "ปิด",
    "รายการ",
    "เลือกแผนการสมัครสมาชิก",
    "ไม่มีสินค้าจำหน่าย",
    "เลือกตัวเลือก",
    "โหลดสินค้าเพิ่มเติม",
    "กำลังเตรียมชุด...",
    "กำลังเปลี่ยนเส้นทาง...",
    "เพิ่มแล้ว",
    "เพิ่ม",
    "ทบทวน",
    "เลือกผลิตภัณฑ์ชุดรวม",
    "ปริมาณ",
    "คุณแน่ใจเหรอ?",
    "คุณแน่ใจหรือไม่ว่าต้องการล้างสินค้าทั้งหมดออกจากรถเข็นของคุณ? การดำเนินการนี้ไม่สามารถยกเลิกได้...",
    "ชัดเจน",
    "ยกเลิก",
    "ล้างรถเข็น",
    "ลบ {{boxSelectionDifference}} รายการเพื่อเลือกกล่องนี้",
    "ลบผลิตภัณฑ์นี้ออกจาก {{stepName}}",
    "เพิ่มผลิตภัณฑ์อย่างน้อย {{conditionQuantity}} รายการในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์สูงสุด {{conditionQuantity}} รายการเพื่อดำเนินการต่อ",
    "เพิ่มผลิตภัณฑ์ {{conditionQuantity}} รายการในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์ที่มีมูลค่าอย่างน้อย {{conditionAmount}} ในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์ที่มีมูลค่าสูงสุด {{conditionAmount}} ในขั้นตอนนี้",
    "เพิ่มสินค้ามูลค่า {{conditionAmount}} ในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์ที่มีน้ำหนักอย่างน้อย {{conditionWeight}} ในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์ที่มีน้ำหนักสูงสุด {{conditionWeight}} ในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์ที่มีน้ำหนัก {{conditionWeight}} ในขั้นตอนนี้",
    "เพิ่มผลิตภัณฑ์เสริมได้สูงสุด {{maxAllowedAddons}} รายการในขั้นตอนนี้",
    "จำเป็นต้องมีผลิตภัณฑ์ Addon ในขั้นตอนนี้",
    "ข้อเสนอเพิ่มเติมที่จะปลดล็อค",
    "เพิ่มลงในรถเข็น",
    "เลือกรุ่น",
    "เพิ่ม x{{allowedQuantity}} แล้ว",
    "เพิ่ม +",
    "เลือก {{quantityDifference}} รายการ",
    "ดูรายการชุดรวม",
    "สินค้าที่เลือกสรร",
    "ผลรวมย่อย",
    "เพิ่มชุดลงในรถเข็น",
    "ก่อนหน้า",
    "เสร็จแล้ว",
    "กำลังเพิ่มชุด...",
    "เพิ่มชุดแล้ว",
    "ผลิตภัณฑ์",
    "แสดงทุกขั้นตอน",
    "ไม่มีสต็อกอีกต่อไป"
  ],
  "tr": [
    "Öğeler",
    "Perakende Fiyatı",
    "Kazanıyorsun",
    "Kutuya Ekle",
    "Sonraki",
    "Sepete ekle",
    "Toplam",
    "Seçilen Ürünleri Görüntüle",
    "kapalı",
    "öğeler)",
    "Abonelik Planını Seçin",
    "Hiçbir Ürün Mevcut Değil",
    "Seçenekleri Seçin",
    "Daha Fazla Ürün Yükle",
    "Paket Hazırlanıyor...",
    "Yönlendiriliyor...",
    "Eklendi",
    "Eklemek",
    "Gözden geçirmek",
    "Paket Ürünlerini Seçin",
    "Miktar",
    "Emin misin?",
    "Sepetinizdeki tüm ürünleri temizlemek istediğinizden emin misiniz? Bu işlem geri alınamaz...",
    "Temizlemek",
    "İptal etmek",
    "Sepeti Temizle",
    "Bu kutuyu seçmek için {{boxSelectionDifference}} öğeyi kaldırın",
    "Bu Ürünü {{stepName}}'den Kaldır",
    "Bu adımda en az {{conditionQuantity}} ürün ekleyin",
    "Devam etmek için maksimum {{conditionQuantity}} ürün ekleyin",
    "Bu adımda tam olarak {{conditionQuantity}} ürün ekleyin",
    "Bu adımda en az {{conditionAmount}} değerindeki ürünleri ekleyin",
    "Bu adımda maksimum {{conditionAmount}} değerindeki ürünleri ekleyin",
    "Bu adımda {{conditionAmount}} değerindeki ürünleri ekleyin",
    "Bu adımda en az {{conditionWeight}} ağırlığındaki ürünleri ekleyin",
    "Bu adımda maksimum {{conditionWeight}} ağırlığındaki ürünleri ekleyin",
    "Bu adımda {{conditionWeight}} ağırlığındaki ürünleri ekleyin",
    "Bu adımda maksimum {{maxAllowedAddons}} eklenti ürünü ekleyin",
    "Bu adımda eklenti ürünü zorunludur",
    "Kilidi açılacak ek teklifler",
    "Sepete ekle",
    "Varyant seçin",
    "x{{allowedQuantity}} eklendi",
    "Ekle +",
    "{{quantityDifference}} Öğeyi Seçin",
    "Paket Öğelerini Görüntüle",
    "Seçilen Ürünler",
    "Ara toplam",
    "Paketi Sepete Ekle",
    "Önceki",
    "Tamamlamak",
    "Paket Ekleniyor...",
    "Paket Eklendi",
    "Ürün",
    "Tüm adımları göster",
    "Artık Stok Yok"
  ],
  "vi": [
    "Mặt hàng",
    "Giá bán lẻ",
    "Bạn lưu",
    "Thêm vào hộp",
    "Kế tiếp",
    "Thêm vào giỏ hàng",
    "Tổng cộng",
    "Xem các sản phẩm đã chọn",
    "tắt",
    "mặt hàng)",
    "Chọn gói đăng ký",
    "Không có sản phẩm nào",
    "Chọn Tùy chọn",
    "Tải thêm sản phẩm",
    "Đang chuẩn bị gói...",
    "Đang chuyển hướng...",
    "Đã thêm",
    "Thêm vào",
    "Ôn tập",
    "Chọn gói sản phẩm",
    "Số lượng",
    "Bạn có chắc không?",
    "Bạn có chắc chắn muốn xóa tất cả các mặt hàng khỏi giỏ hàng của mình không? Không thể hoàn tác hành động này...",
    "Thông thoáng",
    "Hủy bỏ",
    "Xóa giỏ hàng",
    "Xóa {{boxSelectionDifference}} mục để chọn hộp này",
    "Xóa sản phẩm này khỏi {{stepName}}",
    "Thêm ít nhất {{conditionQuantity}} sản phẩm vào bước này",
    "Thêm tối đa {{conditionQuantity}} sản phẩm để tiếp tục",
    "Thêm chính xác {{conditionQuantity}} sản phẩm ở bước này",
    "Thêm sản phẩm có giá trị ít nhất {{conditionAmount}} ở bước này",
    "Thêm sản phẩm có giá trị tối đa {{conditionAmount}} ở bước này",
    "Thêm sản phẩm trị giá {{conditionAmount}} ở bước này",
    "Thêm sản phẩm có trọng lượng tối thiểu {{conditionWeight}} vào bước này",
    "Thêm sản phẩm có trọng lượng tối đa {{conditionWeight}} vào bước này",
    "Thêm sản phẩm có trọng lượng {{conditionWeight}} ở bước này",
    "Thêm tối đa {{maxAllowedAddons}} sản phẩm bổ trợ ở bước này",
    "Sản phẩm addon là bắt buộc ở bước này",
    "Ưu đãi bổ sung sẽ được mở khóa",
    "Thêm vào giỏ hàng",
    "Chọn biến thể",
    "Đã thêm x{{allowedQuantity}}",
    "Thêm +",
    "Chọn {{quantityDifference}} Mục",
    "Xem gói vật phẩm",
    "Sản phẩm được chọn",
    "Tổng phụ",
    "Thêm gói vào giỏ hàng",
    "Trước đó",
    "Xong",
    "Đang thêm gói...",
    "Đã thêm gói",
    "Sản phẩm",
    "Hiển thị tất cả các bước",
    "Không Còn Hàng"
  ],
  "no": [
    "Varer",
    "Utsalgspris",
    "Du sparer",
    "Legg til i boks",
    "Neste",
    "Legg i handlekurven",
    "Total",
    "Se utvalgte produkter",
    "av",
    "vare(r)",
    "Velg Abonnementsplan",
    "Ingen produkter tilgjengelig",
    "Velg Alternativer",
    "Last inn flere produkter",
    "Forbereder pakke...",
    "Omdirigerer...",
    "Lagt til",
    "Legge til",
    "Gjennomgå",
    "Velg pakke produkter",
    "Mengde",
    "Er du sikker?",
    "Er du sikker på at du vil slette alle varer fra handlekurven? Denne handlingen kan ikke angres...",
    "Klar",
    "Kansellere",
    "Tøm handlekurven",
    "Fjern {{boxSelectionDifference}} element(er) for å velge denne boksen",
    "Fjern dette produktet fra {{stepName}}",
    "Legg til minst {{conditionQuantity}} produkter på dette trinnet",
    "Legg til maksimalt {{conditionQuantity}} produkter for å fortsette",
    "Legg til nøyaktig {{conditionQuantity}} produkter på dette trinnet",
    "Legg til produkter verdt minst {{conditionAmount}} på dette trinnet",
    "Legg til produkter verdt maksimalt {{conditionAmount}} på dette trinnet",
    "Legg til produkter verdt {{conditionAmount}} på dette trinnet",
    "Legg til produkter som veier minst {{conditionWeight}} på dette trinnet",
    "Legg til produkter som veier maksimalt {{conditionWeight}} på dette trinnet",
    "Legg til produkter som veier {{conditionWeight}} på dette trinnet",
    "Legg til maksimalt {{maxAllowedAddons}} tilleggsprodukter på dette trinnet",
    "Tilleggsprodukt er obligatorisk på dette trinnet",
    "Ytterligere tilbud som skal låses opp",
    "Legg i handlekurven",
    "Velg variant",
    "Lagt til x{{allowedQuantity}}",
    "Legg til +",
    "Velg {{quantityDifference}} varer",
    "Se pakkeelementer",
    "Utvalgte produkter",
    "Delsum",
    "Legg pakken i handlekurven",
    "Forrige",
    "Ferdig",
    "Legger til pakke ...",
    "Pakke lagt til",
    "Produkt",
    "Vis alle trinn",
    "Ikke mer lager"
  ]
};
